### ISSUE TITLE
Dateshifting for 20 months for  2016,4,X fails. 

### ISSUE THREAD

**Issue by mindreframer** [bitwalker/timex#158]
### Steps to reproduce
```
Timex.date({2016,4,25}) |> Timex.shift(months: 20)
```

### Description of issue

```
** (FunctionClauseError) no function clause matching in :calendar.last_day_of_the_month1/2
    (stdlib) calendar.erl:244: :calendar.last_day_of_the_month1(2018, 0)
     (timex) lib/datetime/datetime.ex:800: Timex.DateTime.shift_by/3
     (timex) lib/datetime/datetime.ex:710: Timex.DateTime.apply_shifts/2
     (timex) lib/date/date.ex:374: Timex.Date.shift/2
```

**Comment by gutschilla** [comment]
addressed in https://github.com/bitwalker/timex/pull/165

**Comment by bitwalker** [comment]
Closing since this has already been fixed.
