### ISSUE TITLE
Format error depending on microseconds value

### ISSUE THREAD

**Issue by santif** [bitwalker/timex#275]
When microsecond part is < 100_000, `Timex.format!()` throws an error

I'm using Erlang 19.2, Elixir 1.4.1 and Timex 3.1.9

```
iex(24)> Timex.now() |> Timex.format!("{YYYY}{0M}{0D}-{h24}:{m}:{s}{ss}")
"20170207-08:59:07.773320"
iex(25)> Timex.now() |> Timex.format!("{YYYY}{0M}{0D}-{h24}:{m}:{s}{ss}")
"20170207-08:59:08.402839"
iex(26)> Timex.now() |> Timex.format!("{YYYY}{0M}{0D}-{h24}:{m}:{s}{ss}")
** (ArgumentError) argument error
            :erlang.binary_part("87422", 0, 6)
    (timex) lib/format/datetime/formatter.ex:524: Timex.Format.DateTime.Formatter.format_token/6
    (timex) lib/format/datetime/formatters/default.ex:183: Timex.Format.DateTime.Formatters.Default.do_format/4
    (timex) lib/format/datetime/formatter.ex:55: Timex.Format.DateTime.Formatter.lformat!/4
iex(26)> Timex.now() |> Timex.format!("{YYYY}{0M}{0D}-{h24}:{m}:{s}{ss}")
** (ArgumentError) argument error
            :erlang.binary_part("62797", 0, 6)
    (timex) lib/format/datetime/formatter.ex:524: Timex.Format.DateTime.Formatter.format_token/6
    (timex) lib/format/datetime/formatters/default.ex:183: Timex.Format.DateTime.Formatters.Default.do_format/4
    (timex) lib/format/datetime/formatter.ex:55: Timex.Format.DateTime.Formatter.lformat!/4
iex(26)> Timex.now() |> Timex.format!("{YYYY}{0M}{0D}-{h24}:{m}:{s}{ss}")
"20170207-08:59:12.919031"
iex(27)> Timex.now() |> Timex.format!("{YYYY}{0M}{0D}-{h24}:{m}:{s}{ss}")
"20170207-08:59:13.972089"
```

**Comment by bitwalker** [comment]
This is now fixed in master, thanks for the report!
