### ISSUE TITLE
Bug in `Timex.set()` with microseconds

### ISSUE THREAD

**Issue by ckruse** [bitwalker/timex#374]
Hi,

I encountered a bug when calling `Timex.set()` with `:microsecond`:

~~~
iex(2)> Timex.set(Timex.now, [microsecond: 0])
** (FunctionClauseError) no function clause matching in Timex.normalize/2

    The following arguments were given to Timex.normalize/2:

        # 1
        :microsecond

        # 2
        0

    Attempted function clauses (showing 10 out of 12):

        def normalize(:date, {year, month, day})
        def normalize(:year, year) when year < 0
        def normalize(:year, year)
        def normalize(:month, month)
        def normalize(:time, {hour, min, sec})
        def normalize(:time, {hour, min, sec, ms})
        def normalize(:hour, hour)
        def normalize(:minute, min)
        def normalize(:second, sec)
        def normalize(:millisecond, ms)

    (timex) lib/timex.ex:1578: Timex.normalize/2
    (timex) lib/datetime/datetime.ex:212: anonymous fn/3 in Timex.Protocol.DateTime.set/2
    (elixir) lib/enum.ex:1811: Enum."-reduce/3-lists^foldl/2-0-"/3
~~~

`:microsecond` is [documented](https://hexdocs.pm/timex/Timex.html#t:set_options/0) and accepted as a valid argument.

**Comment by ckruse** [comment]
Hm, I just noticed (by checking the `microsecond` type link in the documentation) that `:microsecond` expects a tuple of `{microseconds, precision}`. That works. Sorry for the noise…
