### ISSUE TITLE
Unambiguous datetime conversion is considered ambiguous because of DST

### ISSUE THREAD

**Issue by lachezar** [bitwalker/timex#390]
```
iex(15)> "2017-10-28T23:59:43.522Z" |> Timex.parse!("{ISO:Extended:Z}") |> Timex.local
#DateTime<2017-10-29 01:59:43.522+02:00 CEST Europe/Stockholm>
iex(16)> "2017-10-29T00:00:43.522Z" |> Timex.parse!("{ISO:Extended:Z}") |> Timex.local
#<Ambiguous(#DateTime<2017-10-29 02:00:43.522+02:00 CEST Europe/Stockholm> ~ #DateTime<2017-10-29 01:00:43.522+01:00 CET Europe/Stockholm>)>
```

The example above is using timex 3.1.24 and the local time zone is "Europe/Stockholm". 

The source datetime is using UTC (Zulu time) and I believe this means that conversion from it to any other time zone should be always possible, since UTC does not have daylight saving.

I have read through the docs about [Timex.AmbiguousDateTime](https://hexdocs.pm/timex/Timex.AmbiguousDateTime.html#content), but I don't think this issue fits any of the 2 example cases in it.

**Comment by shantiii** [comment]
Your issue seems to relate to this other one: https://github.com/bitwalker/timex/issues/142

Namely, there seems to be an overlap in daylight savings timezone and normal timezone in europe

**Comment by Anichale** [comment]
Also running into this issue, using a pipeline like:

```elixir
datetime = "20171105T01:37:07America/New_York"

datetime
|> Timex.parse!("%Y%m%dT%T%Z", :strftime)
|> Timex.Timezone.convert("UTC")
```
```elixir
** (FunctionClauseError) no function clause matching in Timex.Parse.DateTime.Parser.parse!/3
    (timex) lib/parse/datetime/parser.ex:77: Timex.Parse.DateTime.Parser.parse!("%Y%m%dT%T%Z", :strftime, Timex.Parse.DateTime.Tokenizers.Default)
iex(infusion@127.0.0.1)17> Timex.parse!(datetime, "%Y%m%dT%T%Z", :strftime)
** (FunctionClauseError) no function clause matching in Timex.Parse.DateTime.Parser.apply_directives/3
    (timex) lib/parse/datetime/parser.ex:199: Timex.Parse.DateTime.Parser.apply_directives([], #<Ambiguous(#<DateTime(2017-11-05T01:37:07-04:00 America/New_York)> ~ #<DateTime(2017-11-05T01:37:07-05:00 America/New_York)>)>, Timex.Parse.DateTime.Tokenizers.Strftime)
    (timex) lib/parse/datetime/parser.ex:90: Timex.Parse.DateTime.Parser.parse!/3
```
