### ISSUE TITLE
Elixir 1.8 Deprecation warnings

### ISSUE THREAD

**Issue by fredr** [bitwalker/timex#503]
### Steps to reproduce

- Install Elixir 1.8.0
- Run test suite

### Description of issue

Elixir 1.8 deprecates pluralized time unit atoms, example error:
```
warning: deprecated time unit: :seconds. A time unit should be :second, :millisecond, :microsecond, :nanosecond, or a positive integer
  (elixir) lib/calendar/iso.ex:703: Calendar.ISO.from_unix/2
  (elixir) lib/calendar/datetime.ex:118: DateTime.from_unix/3
  (elixir) lib/calendar/datetime.ex:166: DateTime.from_unix!/3
  test/timezone_test.exs:102: TimezoneTests."test converting across zone boundaries"/1
  (ex_unit) lib/ex_unit/runner.ex:355: ExUnit.Runner.exec_test/1
  (stdlib) timer.erl:166: :timer.tc/1
  (ex_unit) lib/ex_unit/runner.ex:306: anonymous fn/4 in ExUnit.Runner.spawn_test_monitor/4
```

**Comment by fireproofsocks** [comment]
Did hex pick up a new version of this? The warnings still show up with Timex v 3.5.0.  Thanks for keeping this up to date!

**Comment by MCMrARM** [comment]
Any update on a Hex release? It has been quite a bit of time since this has been merged.

**Comment by richeterre** [comment]
@bitwalker Would you be up for making a release with this?

**Comment by bitwalker** [comment]
Done
