### ISSUE TITLE
Error on Timex.Timezone.get when executed inside a migration

### ISSUE THREAD

**Issue by speeddragon** [bitwalker/timex#512]
### Steps to reproduce

- Version: **3.5.0**
- API function called: **Timex.Timezone.get/1**
- Arguments provided: **"Etc/GMT"**

### Description of issue

**What are the expected results?**
Calling `Timex.Timezone.get("Etc/GMT")` should return a `%Timex.TimezoneInfo{}` module, but instead give the following error. This only happen when the code is executed **inside a migration**. I think when `mix ecto.migrate` is execute, the ets table with timezone information is unavailable, even `:local` doesn't work, only `:utc`.

```
pry(1)> Timex.Timezone.get("Europe/Lisbon")
** (ArgumentError) argument error
   (stdlib) :ets.lookup(:tzdata_current_release, :release_version)
   lib/tzdata/release_reader.ex:47: Tzdata.ReleaseReader.current_release_from_table/0
   lib/tzdata/release_reader.ex:14: Tzdata.ReleaseReader.simple_lookup/1
   lib/tzdata/release_reader.ex:7: Tzdata.ReleaseReader.zone_and_link_list/0
   lib/tzdata.ex:40: Tzdata.zone_exists?/1
   lib/timezone/timezone.ex:151: Timex.Timezone.name_of/1
   lib/timezone/timezone.ex:179: Timex.Timezone.get/2
   (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
   (iex) lib/iex/evaluator.ex:257: IEx.Evaluator.handle_eval/5
   (iex) lib/iex/evaluator.ex:237: IEx.Evaluator.do_eval/3
   (iex) lib/iex/evaluator.ex:215: IEx.Evaluator.eval/3
   (iex) lib/iex/evaluator.ex:103: IEx.Evaluator.loop/1
   (iex) lib/iex/evaluator.ex:27: IEx.Evaluator.init/4
   lib/my_app/ecto/datetime_with_timezone.ex:40: MyApp.Ecto.DatetimeWithTimezone.load/1
   (ecto) lib/ecto/type.ex:801: Ecto.Type.process_loaders/3
   (ecto) lib/ecto/schema/loader.ex:94: Ecto.Schema.Loader.adapter_load/6
   (ecto) lib/ecto/repo/queryable.ex:193: anonymous fn/5 in Ecto.Repo.Queryable.preprocessor/3
   (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
   (ecto) lib/ecto/repo/queryable.ex:152: Ecto.Repo.Queryable.execute/4
```

**Comment by bitwalker** [comment]
You need to make sure Timex/Tzdata are started with `Application.ensure_all_started(:timex)`
