### ISSUE TITLE
Timex.parse with {kitchen} breaks when the hour is 2 digits

### ISSUE THREAD

**Issue by paulstatezny** [bitwalker/timex#615]
First off, thank you for Timex!

## Steps to reproduce

- API function called: `Timex.parse!`
- Arguments provided: `"10:00AM", "{kitchen}"`

### Expected results

Returns `~N[2020-09-18 10:00:00]` (date would change depending on the day you run it).

### Actual results

```
** (Timex.Parse.ParseError) Expected `:`, but found `0` at line 1, column 2.
    (timex) lib/parse/datetime/parser.ex:110: Timex.Parse.DateTime.Parser.parse!/3
```

## Commentary

Basically, the problem is that you can `Timex.format!` a time with `{kitchen}`, but then when you `Timex.parse!` the output with `{kitchen}` it crashes if the hour (in the string) is a 2-digit number such as `12` or `10`.

Another demonstration from a different angle:

```
iex> ~T[01:00:00] |> Timex.format!("{kitchen}") |> Timex.parse!("{kitchen}")
~N[2020-09-18 01:00:00]

iex> ~T[02:00:00] |> Timex.format!("{kitchen}") |> Timex.parse!("{kitchen}")
~N[2020-09-18 02:00:00]

iex> ~T[09:00:00] |> Timex.format!("{kitchen}") |> Timex.parse!("{kitchen}")
~N[2020-09-18 09:00:00]

iex> ~T[10:00:00] |> Timex.format!("{kitchen}") |> Timex.parse!("{kitchen}")
** (Timex.Parse.ParseError) Expected `:`, but found `2` at line 1, column 2.
    (timex) lib/parse/datetime/parser.ex:110: Timex.Parse.DateTime.Parser.parse!/3

iex> ~T[00:00:00] |> Timex.format!("{kitchen}") |> Timex.parse!("{kitchen}")
** (Timex.Parse.ParseError) Expected `:`, but found `2` at line 1, column 2.
    (timex) lib/parse/datetime/parser.ex:110: Timex.Parse.DateTime.Parser.parse!/3
```

## Workaround

If anyone else if having this problem, I've found you can do this instead:

```elixir
Timex.parse!("10:00AM", "{h12}:{m}{AM}")
```

For example:

```
iex(70)> ~T[00:00:00] |> Timex.format!("{kitchen}") |> Timex.parse!("{h12}:{m}{AM}")
~N[0000-01-01 00:00:00]
```

**Comment by paulstatezny** [comment]
Thank you 🙂
