### ISSUE TITLE
Timex.to_datetime bug with empty tz

### ISSUE THREAD

**Issue by parallel588** [bitwalker/timex#654]
mix.exs:
```elixir
defp deps do
    [
      {:ecto, "~> 3.5"},
      {:timex, "~> 3.7"}
      ....
  ```
  
  error: 
  ```elixir
  Interactive Elixir (1.11.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Timex.to_datetime(Timex.parse!("2019-02-21T12:00:00", "{ISO:Extended}"), "")
** (FunctionClauseError) no function clause matching in Timex.Parse.Timezones.Posix.finalize/1    
    
    The following arguments were given to Timex.Parse.Timezones.Posix.finalize/1:
    
        # 1
        nil
    
    Attempted function clauses (showing 3 out of 3):
    
        defp finalize(%Timex.PosixTimezone{std_abbr: std, std_offset: soffs, dst_abbr: dst, dst_offset: nil} = tz) when is_binary(dst)
        defp finalize(%Timex.PosixTimezone{std_abbr: std, std_offset: soffs, dst_abbr: nil, dst_offset: nil} = tz)
        defp finalize(%Timex.PosixTimezone{name: nil, std_abbr: std, std_offset: soffs, dst_abbr: dst, dst_offset: doffs} = tz)
    
    (timex 3.7.3) lib/parse/posix/parser.ex:69: Timex.Parse.Timezones.Posix.finalize/1
    (timex 3.7.3) lib/parse/posix/parser.ex:65: Timex.Parse.Timezones.Posix.parse/1
    (timex 3.7.3) lib/timezone/timezone.ex:713: Timex.Timezone.lookup_posix/1
    (timex 3.7.3) lib/timezone/timezone.ex:228: Timex.Timezone.name_of/1
    (timex 3.7.3) lib/timezone/timezone.ex:257: Timex.Timezone.get/2
    (timex 3.7.3) lib/timezone/timezone.ex:563: Timex.Timezone.convert/2
    (timex 3.7.3) lib/datetime/naivedatetime.ex:35: Timex.Protocol.NaiveDateTime.to_datetime/2

  ```
  
  expected:
  
  ```elixir
 Interactive Elixir (1.11.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Timex.to_datetime(Timex.parse!("2019-02-21T12:00:00", "{ISO:Extended}"), "")
{:error, {:invalid_timezone, ""}}
iex(2)>
  ```

**Comment by parallel588** [comment]
fixed here: https://github.com/bitwalker/timex/pull/655
