### ISSUE TITLE
Timex.parse("2100-01-01T00:00:00.000+08:00", "{ISO:Extended}") raises ArgumentError

### ISSUE THREAD

**Issue by angelsl** [bitwalker/timex#658]
### Steps to reproduce

```
iex(2)> Timex.parse("2100-01-01T00:00:00.000+08:00", "{ISO:Extended}")
** (ArgumentError) argument error
    :erlang.hd([])
    (tzdata 1.1.0) lib/tzdata/far_future_dynamic_periods.ex:22: Tzdata.FarFutureDynamicPeriods.zone_in_30_years_in_eternal_period?/1
    (tzdata 1.1.0) lib/tzdata.ex:230: Tzdata.possible_periods_for_zone_and_time/3
    (tzdata 1.1.0) lib/tzdata.ex:196: Tzdata.periods_for_time/3
    (tzdata 1.1.0) lib/tzdata/time_zone_database.ex:32: Tzdata.TimeZoneDatabase.time_zone_periods_from_wall_datetime/2
    (timex 3.7.3) lib/timezone/database.ex:36: Timex.Timezone.Database.time_zone_periods_from_wall_datetime/2
    (elixir 1.11.3) lib/calendar/datetime.ex:438: DateTime.from_naive/3
    (timex 3.7.3) lib/timezone/timezone.ex:551: Timex.Timezone.convert/2
    (timex 3.7.3) lib/parse/datetime/parser.ex:124: Timex.Parse.DateTime.Parser.do_parse/3
    (timex 3.7.3) lib/parse/datetime/parser.ex:95: Timex.Parse.DateTime.Parser.parse!/3
    (timex 3.7.3) lib/parse/datetime/parser.ex:58: Timex.Parse.DateTime.Parser.parse/3
```

### Description of issue

Expected success.

With 3.6.4:

```
iex(1)> Timex.parse("2100-01-01T00:00:00.000+08:00", "{ISO:Extended}")
{:ok, #DateTime<2100-01-01 00:00:00.000+08:00 +08 Etc/GMT-8>}
```

**Comment by mkarnebeek** [comment]
Same for `Timex.parse("2099-01-01T00:00:00.000+01:00", "{ISO:Extended}")`. Broken since 3.7.2, was working in 3.7.1
