### ISSUE TITLE
Error with parse strftime

### ISSUE THREAD

**Issue by hamann** [bitwalker/timex#66]
We have a JS client which sends date strings like 'Mon Jul 06 2015 00:00:00 GMT+0200 (CEST)' (`date.toString()`)

Trying to parse it I get an error

```elixir
iex(3)> date = "Mon Jul 06 2015 00:00:00 GMT+0200 (CEST)"
"Mon Jul 06 2015 00:00:00 GMT+0200 (CEST)"
iex(4)> Timex.DateFormat.parse!(date,"%a %b %d %Y %H:%M:%S %Z%z (%Z)", :strftime)
** (EXIT from #PID<0.1164.0>) an exception was raised:
    ** (ArgumentError) argument error
        :erlang.byte_size([message: "Invalid value for zoffs. Does not match specification for ~r/^[-+]\\d{2}([:]?\\d{2})?$/"])
        (elixir) lib/exception.ex:106: Exception.format_banner/3
        (iex) lib/iex/evaluator.ex:158: IEx.Evaluator.print_error/3
        (iex) lib/iex/evaluator.ex:95: IEx.Evaluator.eval/2
        (iex) lib/iex/evaluator.ex:29: IEx.Evaluator.loop/1
        (iex) lib/iex/evaluator.ex:19: IEx.Evaluator.start/2
```

whereas this works
```elixir
iex(1)> date = "Mon Jul 06 2015 00:00:00 GMT +0200 (CEST)"
"Mon Jul 06 2015 00:00:00 GMT +0200 (CEST)"
iex(2)> Timex.DateFormat.parse!(date,"%a %b %d %Y %H:%M:%S %Z %z (%Z)", :strftime)
%Timex.DateTime{calendar: :gregorian, day: 6, hour: 0, minute: 0, month: 7, ms: 0, second: 0,
 timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min, full_name: "UTC", offset_std: 0, offset_utc: 0,
  until: :max}, year: 2015}
```

**Comment by bitwalker** [comment]
On it, thanks!

**Comment by bitwalker** [comment]
This is fixed in master now, I'll release a new version of timex shortly, I just have one other bug to address. Thanks again for reporting!
