### ISSUE TITLE
Cant compile timex on a project with gettext configured

### ISSUE THREAD

**Issue by ggarciajr** [bitwalker/timex#751]
### Steps to reproduce

- Have gettext as dependency in the appplication
- Define a custom gettetext Plural module
- Try to add timex as dependency

### Versions I'm using
- Elixir 1.15.6
- Timex 3.7
- Gettext 0.23

### Description of issue

- What are the expected results?
Successfully add and timex to the application and be able to use it.

Here is the error I'm getting when trying to add timex to my project

```
== Compilation error in file lib/l10n/gettext.ex ==
** (ArgumentError) could not load module Flash.Gettext.Plural due to reason :unavailable
    (elixir 1.15.7) lib/code.ex:1888: Code.ensure_compiled!/1
    (gettext 0.23.1) lib/gettext/plural.ex:371: Gettext.Plural.plural_info/3
    (gettext 0.23.1) lib/gettext/compiler.ex:571: Gettext.Compiler.compile_plural_forms/4
    (gettext 0.23.1) lib/gettext/compiler.ex:509: Gettext.Compiler.compile_po_file/5
    (gettext 0.23.1) lib/gettext/compiler.ex:450: Gettext.Compiler.compile_unified_po_file/4
    (elixir 1.15.7) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (gettext 0.23.1) expanding macro: Gettext.Compiler.__before_compile__/1
    lib/l10n/gettext.ex:1: Timex.Gettext (module)
could not compile dependency :timex, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile timex --force", update it with "mix deps.update timex" or clean it with "mix deps.clean timex"
```

`Flash.Gettext.Plural` is my custom Plural module and it is defined in my application

Every time I try to run `mix compile` or `mix deps.compile timex --force` I get the same error

**Comment by ggarciajr** [comment]
I figured I had to change how I was configuring gettext pluralization rules.

I had to change my setup from:

```
# config.exs
# For example, in config/config.exs
config :gettext, :plural_forms, MyApp.Plural
```

to

```
defmodule MyApp.Gettext do
  use Gettext, otp_app: :my_app, plural_forms: MyApp.Plural
end
```
